### ISSUE TITLE
Not possible to integrate LK Südliche Weinstraße

### ISSUE THREAD

**Issue by janseb2411** [fhinder/MMM-RKI-Covid19#4]
Hey, 
i don´t know why, but it´s not possible to integrate LK Südliche Weinstraße. Other counties are working without any problems...
Maybe u can take a look :) Landau and Rheinland-Pfalz are shown on the MMM. I also tried out other counties and they are working...

{
	module: "MMM-RKI-Covid19",
	position: "top_bar",
	config:{
		reloadInterval: 60*60*1000,
		tableClass: "small",
		counties: [		
			'SK Landau i.d.Pfalz',
                        'LK Südliche Weinstraße',
                        		],
		states: [
			'Rheinland-Pfalz',
                ]
	}
},

**Comment by KristjanESPERANTO** [comment]
Your configuration works fine for me. I see values for LK Südliche Weinstraße.

Are you using the current version?

![Bildschirmfoto von 2021-05-08 23-00-07](https://user-images.githubusercontent.com/35647502/117553970-02c36280-b055-11eb-8d43-a7eebe678a75.png)

**Comment by janseb2411** [comment]
Yes, I´m using the current version. You used exactly my config? i can´t understand this issue...

**Comment by KristjanESPERANTO** [comment]
Yes, that's strange. I used exactly your configuration for the test. I chose a different position only for the screenshot ("top_right").

**Comment by KristjanESPERANTO** [comment]
Just an idea: Is your config file UTF8 encoded?

You can test this with the following command `file -bi config.js` in your config folder.

The result should be this: `text/plain; charset=utf-8`.

**Comment by janseb2411** [comment]
the result is iso-8859-1, not utf-8

**Comment by KristjanESPERANTO** [comment]
Okay, that's the problem :fireworks: Make a backup of your config file and then try this (in your config folder) to convert the config file to utf-8:

`iconv -f iso-8859-1 -t utf-8 config.js`

**Comment by janseb2411** [comment]
ok, i tried it out but it´s still iso-...

**Comment by KristjanESPERANTO** [comment]
iconv sometimes don't works like I want ^^ Okay, next try:

1. make backup:
`cp conig.js config.bak`

2. Convert and override the config.js
`iconv -f iso-8859-1 -t utf-8 config.bak > config.js`

3. Test again:
`file -bi config.js`

**Comment by janseb2411** [comment]
ok, that finally worked. thx a lot for your time!

**Comment by KristjanESPERANTO** [comment]
You're welcome! :slightly_smiling_face: 

Did the conversion only work or does the module work now and shows your 'Landkreis'? Sometimes the umlauts gets broken when converting, then you just have to open the config file and rewrite the umlauts.

When everything works fine, you can close the ticket. Enjoy this sunny Sunday!

**Comment by janseb2411** [comment]
Also the Landkreis Südliche Weinstraße works now, so my issue is solved!!
