### ISSUE TITLE
Make header optional

### ISSUE THREAD

**Issue by sthuber90** [fhinder/MMM-RKI-Covid19#5]
Maybe it's just a personal preference but I prefer to use modules without their headers. I know which modules I use and where I placed them, therefore a header such as "RKI Daten" doesn't provide any value to me.

Could we add the option to disable it? This could be done for instance in the configuration by setting 'header: ""' in the config. If this is set no header is shown. Optionally, we could still show the header if the RKI numbers are not from today, which would only require to modify the if-clause in the _getHeader_ function a bit.

**Comment by fhinder** [comment]
Hello @sthuber90 ,
can you please varify, that the new possabilities in the configuration fit to your request?
I suggest for your config:

header: "",
config:{
   showUpdateTimestampInHeader: false
}

Best

**Comment by sthuber90** [comment]
Thank you for the quick response and fix. I think this'll do. I was more thinking of something in the direction of:
``` javascript
getHeader: function () {
        // show date in header only if date exists and is not today's date
        if (this.dataRKI.lastUpdate
            && !((new Date(this.dataRKI.lastUpdate)).setHours(0, 0, 0, 0) === (new Date()).setHours(0, 0, 0, 0))) {
            return "RKI-Daten von " + this.dataRKI.lastUpdate;
        }
        // header: '' will hide the header
        return typeof this.data.header !== 'undefined' ? this.data.header : "RKI-Daten";
},
```

So with a configuration such as:

``` js
{
     module: "MMM-RKI-Covid19",
     header: '',
}
```
... you won't see the header, unless the date of the data is not today's date.

But to be clear: I think your solution is just fine as is
