### ISSUE TITLE
Add license to allow Open Source usage

### ISSUE THREAD

**Issue by sthuber90** [fhinder/MMM-RKI-Covid19#6]
How do you feel about adding the Apache 2.0 or MIT license to your repo to allow Open Source usage? I believe, strictly speaking, it wouldn't even be allowed - legally - to fork your repository and modify your code or use it without your consent. 

To add a license it should be enough if you add either a LICENSE.md file containing the license text you want to support or to run _npm init_ and set the license name in the generated _package.json_.

**Comment by fhinder** [comment]
Hello @sthuber90 ,
I added the MIT license.
Best
